# Generated by Django 3.2.12 on 2023-02-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassView', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User1',
        ),
    ]
