# Generated by Django 3.2.12 on 2023-02-24 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ClassView', '0002_rename_user_user1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('First_name', models.CharField(default='', max_length=200)),
                ('Last_name', models.CharField(default='', max_length=200)),
                ('Username', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Confirm_password', models.CharField(max_length=200)),
            ],
        ),
    ]
