# Generated by Django 3.2.12 on 2023-02-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassView', '0005_auto_20230224_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Confirm_password',
            new_name='re_password',
        ),
    ]
